apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  initContainers:
  - name: download-file
    image: alpine:latest
    command: ['sh', '-c', 'wget -O /data/myfile.txt https://raw.githubusercontent.com/BGLCorp/devops-interview-tests/main/myfile.txt']
    volumeMounts:
    - mountPath: /data
      name: temp
  containers:
  - name: myapp-container
    image: alpine:latest
    command: ['sh', '-c', 'cat /data/myfile.txt']
    volumeMounts:
    - mountPath: /data
      name: temp
  volumes:
  - emptyDir: {}
    name: temp